services:
  postgres:
    image: postgres:16
    container_name: postgres-books
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - books-network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

#  app:
#    build: .
#    container_name: books-app
#    depends_on:
#      - postgres
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/books_db
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "8080:8080"
#    networks:
#      - books-network

networks:
  books-network:
    driver: bridge
