### GET ALL BOOKS
GET http://localhost:8080/v1/api/books

### GET ALL BOOKS BY USER
GET http://localhost:8080/v1/api/books/user/00000000-0000-0000-0000-000000000001

### ADD A BOOK BY ISBN 1
POST http://localhost:8080/v1/api/books/isbn/0765365278

### ADD A BOOK BY ISBN 2
POST http://localhost:8080/v1/api/books/isbn/9780544003415

### ADD A BOOK BY ISBN 3
POST http://localhost:8080/v1/api/books/isbn/0062225677

### ADD A BOOK MANUALLY
#POST http://localhost:8080/v1/api/books
#Content-Type: application/json

### GET A BOOK BY ID:
#GET http://localhost:8080/v1/api/books/1

### GET A BOOK BY ISBN:
GET http://localhost:8080/v1/api/books/isbn/9780618640157


### GET RECOMMENDATIONS
GET http://localhost:8080/v1/api/recommend/00000000-0000-0000-0000-000000000001